bing:
  search:
    subscription:
      key: ${BING_SEARCH_SUBSCRIPTION_KEY:}
petstore:
  service:
    pet:
     url: ${PETSTOREPETSERVICE_URL:http://localhost:8081}
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    order:
      url: ${PETSTOREORDERSERVICE_URL:http://localhost:8083}
  logging:
    additional-headers-to-log: ${PETSTORE_ADDITIONAL_HEADERS_TO_LOG:}
    additional-headers-to-send: ${PETSTORE_ADDITIONAL_HEADERS_TO_SEND:}
  signalR:
    negotiation-url: ${SIGNALR_NEGOTIATION_URL:}
    service-url: ${SIGNALR_SERVICE_URL:}
    key: ${SIGNALR_SERVICE_KEY:}
    update:
      fixedRate: ${SIGNALR_UPDATE_FIXEDRATE:60000}
server:
  port: ${PETSTOREAPP_SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
spring:
  application:
    name: petstoreapp
  thymeleaf:
    cache: false
  cache:
    cache-names: currentUsers
  cloud:
    azure:
      activedirectory:
        b2c:
          enabled: true
          baseUri: https://fowlart.b2clogin.com/fowlart.onmicrosoft.com
          credential:
            client-id: ${PETSTOREAPP_B2C_CREDENTIAL_CLIENT_ID}
            client-secret: ${PETSTOREAPP_B2C_CREDENTIAL_CLIENT_SECRET}
          login-flow: sign-up-or-sign-in
          reply-url: https://fowlart-pet-store.azurewebsites.net/login
          user-flows:
            sign-up-or-sign-in: B2C_1_pet-store-user-flow
            #profile-edit: B2C_1_profileediting
            #password-reset: B2C_1_passwordreset
          logout-success-url: https://fowlart-pet-store.azurewebsites.net/
