springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PetstoreorderserviceServerPort}

petstore:
  service:
    product:
      url: ${PetstoreproductserviceUrl}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    azure:
      cosmos:
        endpoint: https://fowlart-cosmosdb.documents.azure.com:443/
        # get value from Key Vault
        key: ${CosmosDBKey}
        database: petstore
      keyvault:
        secret:
          property-source-enabled: true
          property-sources:
            - endpoint: https://fowlart-key-vault.vault.azure.net/

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
azure.application-insights:
  instrumentation-key: 3e0ce15e-9eb8-44b6-b6bc-f09b3d975f36
