springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PetstoreorderserviceServerPort}

petstore:
  service:
    product:
      url: ${PetstoreproductserviceUrl}

spring:
  application:
    name: fowlart-order-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    azure:
      keyvault:
        endpoint: https://fowlart-key-vault.vault.azure.net/
        credential:
          managed-identity-enabled: true
        secret:
          property-source-enabled: true
          property-sources:
            - endpoint: https://fowlart-key-vault.vault.azure.net/
              secret-keys: CosmosDBKey, PetstoreproductserviceUrl, PetstoreorderserviceServerPort
      cosmos:
        endpoint: https://fowlartcosmos.documents.azure.com:443/
        key: ${CosmosDBKey}
        database: petstore

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
