springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    azure:
      cosmos:
        endpoint: https://fowlartcosmos.documents.azure.com:443/
        key: ${COSMOSDB_KEY}
        database: petstore
servicebus:
  connection-string: ${SERVICEBUS_CONNECTION_STRING}
  queue:
    name: pet_store_order_queue
management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
